# Generated by Django 4.1.7 on 2023-03-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.IntegerField()),
                ('course_name', models.CharField(max_length=250)),
                ('semester_or_year', models.CharField(max_length=250)),
                ('no_of_year', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(blank=True, max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('father_name', models.CharField(max_length=250)),
                ('mobile_no', models.IntegerField()),
                ('session', models.CharField(max_length=250)),
                ('applicant_status', models.CharField(max_length=100)),
                ('application_status', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('admission_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.course')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.IntegerField()),
                ('subject_name', models.CharField(max_length=250)),
                ('semester', models.IntegerField()),
                ('credit_hours', models.IntegerField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.course')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(blank=True, max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('mobile_no', models.IntegerField()),
                ('session', models.CharField(max_length=250)),
                ('teacher_status', models.CharField(max_length=100)),
                ('application_status', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('hire_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.course')),
            ],
            options={
                'db_table': 'teacher_info',
            },
        ),
        migrations.CreateModel(
            name='Teacher_salary_allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.FloatField()),
                ('medical_allowance', models.FloatField()),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.teacher')),
            ],
            options={
                'db_table': 'teacher_salary_allowance',
            },
        ),
        migrations.CreateModel(
            name='Teacher_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(max_length=250)),
                ('paid_date', models.DateTimeField()),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.teacher')),
            ],
            options={
                'db_table': 'teacher_salary',
            },
        ),
        migrations.CreateModel(
            name='Subject_of_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField()),
                ('total_classes', models.IntegerField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.course')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.teacher')),
            ],
            options={
                'db_table': 'teacher_subject',
            },
        ),
        migrations.CreateModel(
            name='Student_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_voucher', models.IntegerField()),
                ('amount', models.FloatField(max_length=100)),
                ('posting_date', models.DateTimeField()),
                ('status', models.CharField(max_length=250)),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.student')),
            ],
            options={
                'db_table': 'student_fee',
            },
        ),
        migrations.CreateModel(
            name='Course_of_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.course')),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.student')),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.subject')),
            ],
            options={
                'db_table': 'student_course',
            },
        ),
    ]
