# Generated by Django 4.1.7 on 2023-03-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student_info',
        ),
    ]
