# Generated by Django 4.1.7 on 2023-04-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0005_rename_course_id_student_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(blank=True, upload_to='Images/'),
        ),
    ]
