# Generated by Django 4.1.7 on 2023-04-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0011_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, upload_to='Images/Teachers'),
        ),
    ]
